Traceback (most recent call last):
  File "/home/daineto/CostFOND/planner/planner.py", line 237, in update_g_brute
    loopy_states = set().union(*cycles)
MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError

During handling of the above exception, another exception occurred:

MemoryError
real 241.28
user 233.63
sys 10.24
